{% set name = "twitchAPI" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ce5f2e384768b665fe6ccf339ffe7fc14ced4cc04302440b864bf1ffbf72c11

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - aiohttp
    - python >={{ python_min }}
    - python-dateutil
    - requests
    - typing_extensions
    - websockets

test:
  requires:
    - python {{ python_min }}
  imports:
    - twitchAPI

about:
  home: https://github.com/Teekeks/pyTwitchAPI
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python 3.7+ implementation of the Twitch Helix API, its Webhook, PubSub and EventSub
  doc_url: https://pytwitchapi.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/Teekeks/pyTwitchAPI

extra:
  recipe-maintainers:
    - ning-y
